// This file is auto-generated by scripts/createDemoRegistry.js
export const registry = {
  'Toasts-ios': {
    component: () => import('./Toasts-ios.svelte').then((m) => m.default),
    raw: () => import('./Toasts-ios.svelte?raw').then((m) => m.default)
  },
  Button: {
    component: () => import('./Button.svelte').then((m) => m.default),
    raw: () => import('./Button.svelte?raw').then((m) => m.default)
  }
};
