// This file is auto-generated by scripts/createDemoRegistry.js
export const registry = {
  'Toasts-ios': {
    component: () => import('./Toasts-ios.svelte').then((m) => m.default),
    raw: () => import('./Toasts-ios.svelte?raw').then((m) => m.default)
  },
  Button: {
    component: () => import('./Button.svelte').then((m) => m.default),
    raw: () => import('./Button.svelte?raw').then((m) => m.default)
  },
  Spinner: {
    component: () => import('./Spinner.svelte').then((m) => m.default),
    raw: () => import('./Spinner.svelte?raw').then((m) => m.default)
  },
  Tooltip: {
    component: () => import('./Tooltip.svelte').then((m) => m.default),
    raw: () => import('./Tooltip.svelte?raw').then((m) => m.default)
  },
  Tree: {
    component: () => import('./Tree.svelte').then((m) => m.default),
    raw: () => import('./Tree.svelte?raw').then((m) => m.default)
  },
  Collapsible: {
    component: () => import('./Collapsible.svelte').then((m) => m.default),
    raw: () => import('./Collapsible.svelte?raw').then((m) => m.default)
  },
  CollapsibleGroup: {
    component: () => import('./Collapsible-group.svelte').then((m) => m.default),
    raw: () => import('./Collapsible-group.svelte?raw').then((m) => m.default)
  },
  CollapsibleIcon: {
    component: () => import('./Collapsible-icon.svelte').then((m) => m.default),
    raw: () => import('./Collapsible-icon.svelte?raw').then((m) => m.default)
  }
};
