#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/snap/codium/440/usr/share/codium/codium" "/home/angus/.config/VSCodium/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscodium://github.copilot-chat" "" "$@"