// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
  'test': {
    name: 'test',
    component: () =>
      import('./lib/components/test.svelte').then((m) => m.default),
    files: ['../lib/registry/default/example/accordion-demo.svelte'],
    raw: () =>
      import('./lib/registry/default/example/accordion-demo.svelte?raw').then((m) => m.default)
  }
};
