# Configuring : https://starship.rs/config/
# Symbols see : https://www.nerdfonts.com/cheat-sheet
# Colors (see https://nordui.netlify.app/docs/core/colors) :


format = """
[](nord-7)\
$os\
[ ](fg:nord-7 bg:nord-1)\
$directory\
[](fg:nord-1)\
$git_branch\
$nodejs\
$python\
$fill\
$status\
$cmd_duration
$character\
"""

add_newline = false
palette = 'nord'

[palettes.nord]
nord-0 = "#2E3440"
nord-1 = "#3B4252"
nord-2 = "#434C5E"
nord-3 = "#4C566A"
nord-4 = "#D8DEE9"
nord-5 = "#E5E9F0"
nord-6 = "#ECEFF4"
nord-7 = "#8FBCBB"
nord-8 = "#88C0D0"
nord-9 = "#81A1C1"
nord-10 = "#5E81AC"
nord-11 = "#BF616A"
nord-13 = "#EBCB8B"
nord-14 = "#A3BE8C"
nord-15 = "#B48EAD"


[os]
format = "[ $symbol ](bg:nord-7 fg:nord-0)"
disabled = false

[os.symbols]
AlmaLinux = " "
Alpine = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
Illumos = " "
Kali = "  "
Linux = " "
Macos = " "
Manjaro = " "
Mint = "󰣭 "
NixOS = "❄️ "
OpenBSD = " "
openSUSE = " "
Pop = " "
Redhat = " "
RedHatEnterprise = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = " "

[directory]
home_symbol = "  "
style = "bg:nord-1"
format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = ' '
style = "nord-10"
truncation_length = 6
truncation_symbol = ''
format = " [$symbol$branch]($style)"

[nodejs]
symbol = "[ ](nord-13)"
style = "nord-10"
format =" [${symbol}($version )]($style)"

[python]
symbol = "[ ](nord-13)"
style = 'nord-10'
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[fill]
symbol = ' '

[status]
symbol = '[ ](bold nord-11)'
not_found_symbol = ''
sigint_symbol="[󰟾 ](bold nord-11)"
success_symbol = ''
format = '$symbol$signal_name$maybe_int'
map_symbol = true
disabled = false

[cmd_duration]
min_time = 100
show_milliseconds = false
disabled = false
format = "[](nord-7)[$duration](bg:nord-7 fg:nord-0)[ ](fg:nord-7)"

[character]
success_symbol = "[λ](bold nord-4)"
error_symbol = "[λ](bold red)"
