# Colors (see https://nordui.netlify.app/docs/core/colors) :
# Base colos :
#2E3440
#3B4252
#434C5E
#4C566A

# Lighter colors
#8FBCBB
#88C0D0
#81A1C1
#5E81AC

# Red : #BF616A
# Green : #A3BE8C

format = """
[](#8FBCBB)\
$os\
[ ](fg:#8FBCBB bg:#3B4252)\
$directory\
[](fg:#3B4252)\
$git_branch\
$nodejs\
$python\
$fill\
$status\
$cmd_duration
$character\
"""

add_newline = false

[os]
format = "[ $symbol ](bg:#8FBCBB fg:#000000)"
disabled = false

[os.symbols]
AlmaLinux = " "
Alpine = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
Illumos = " "
Kali = "  "
Linux = " "
Macos = " "
Manjaro = " "
Mint = "󰣭 "
NixOS = "❄️ "
OpenBSD = " "
openSUSE = " "
Pop = " "
Redhat = " "
RedHatEnterprise = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = " "

[directory]
style = "bg:#3B4252"
home_symbol = "  "
format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
style = "#5E81AC"
symbol = ' '
truncation_length = 6
truncation_symbol = ''
format = " [$symbol$branch]($style)"

[nodejs]
# symbol = " "
style = "green"
format =" [$symbol($version )]($style)"

[python]
symbol = " "
style = '#5E81AC'
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[fill]
symbol = ' '

[status]
symbol = '[ ](bold #BF616A)'
not_found_symbol = ''
success_symbol = ''
format = '$symbol$signal_name$maybe_int'
map_symbol = true
disabled = false

[cmd_duration]
min_time = 100
show_milliseconds = false
disabled = false
format = "[](#8FBCBB)[$duration](bg:#8FBCBB fg:#000000)[ ](fg:#8FBCBB)"

[character]
success_symbol = "[λ](bold fg:#3B4252)"
error_symbol = "[λ](bold red)"
