// This file is auto-generated by scripts/createDemoRegistry.js
export const registry = {
  commands: {
    component: () => import('./s.svelte').then((m) => m.default),
    raw: () => import('./s.svelte?raw').then((m) => m.default)
  },
  dropdown: {
    component: () => import('./dropdown.svelte').then((m) => m.default),
    raw: () => import('./dropdown.svelte?raw').then((m) => m.default)
  },
  tree: {
    component: () => import('./tree.svelte').then((m) => m.default),
    raw: () => import('./tree.svelte?raw').then((m) => m.default)
  },
};
